name: example
description: Example project for wagmi_flutter_web
publish_to: "none"

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  js: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  reown_flutter_web:
    path: ../

flutter:
  uses-material-design: true
  # assets:
  # - assets/
