name: reown_flutter_web
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  decimal: ^3.2.1
  flutter:
    sdk: flutter
  web: ^1.1.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8

  freezed: ^2.5.2

  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
