name: reown_flutter_web
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  decimal: ^3.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
